### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Pietro395** [evanmiller/fmptools#6]
I compiled and installed the application, but I can't find the tools installed, the installer tells me they should be in /usr/local/bin

I am using Ubuntu 21.10.

Where am I doing wrong?

**Comment by evanmiller** [comment]
Hi, each of the command-line tools requires an external library. So you'll need to make sure you have yajl, sqlite, and/or libxlsxwriter installed (maybe `-dev` versions on Ubuntu) before compiling. Without those, only the C library will be installed.

**Comment by Pietro395** [comment]
Thanks for the support, I was able to install it
