### ISSUE TITLE
Fields in an .fp7 file partially empty

### ISSUE THREAD

**Issue by bouscram** [evanmiller/fmptools#8]
Hi. I am trying to convert a .fp7 file containing about 2500 cooking recipes. Its structure is fairly simple (8 text fields + 1 image field), and I have the following issue with both  fp2excel and fp2sqlite:

- Text fields with short contents (title, source URL, category, ...) seem correctly extracted
- Text fields with a longer content (ingredients, recipe itself) are either partially extracted, or most of the times empty.

I don't know if you still maintain these (very useful) tools, but if you are, I would be glad if you could fix this issue.
I can provide the original file (it's more than 4GB because of the embedded images), as well as the output files, but I'l have to create a share to do so - so I'll wait for an answer before doing so.

**Comment by evanmiller** [comment]
Hi, thanks for the report. 4GB is certainly getting to the outer edges of what I have tested with the library – I'm not actively adding features, but I do try to fix bugs when I have the opportunity. I am traveling for the next few weeks so I will be unlikely to address this immediately. Please feel free to add another comment here in mid-December and I'll see about improving support for long text fields over the holidays.

**Comment by bouscram** [comment]
In fact the file itself is very large, but the problematic fields are not so big - imagine how long a typical recipe is.
You can find a .zip with the files here : https://www.jottacloud.com/s/1370e894e4e9d8f4476954c6e3cd1f53b38

(btw. the conversion process is very fast on my M1 Mac Mini, even for such a large file - I was impressed)

I don't have access to Filemaker any more, so I can't look if there is something special about these fields

**Comment by evanmiller** [comment]
Hi, using the file that you provided, I made some improvements to the code today in order to better handle long text fields. If you still see problems in the converted file after updating the `master` branch, please let me know. 

Here's a sample of what I see now:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/134711/208251469-1293b59e-9b01-445b-a890-e1c9f8eab952.png">

**Comment by bouscram** [comment]
Thanks a lot! It seems perfectly correct and good for release. I tried the Excel and Sqlite conversions, both are ok.
