### ISSUE TITLE
Running extremely slow on large fmp12 data file

### ISSUE THREAD

**Issue by ye** [evanmiller/fmptools#9]
Hi,

I've downloaded the source code from the git today and compiled it on a Mac Min (Apple M1 chip) with 8 GB physical memory.

The data file is a 9.3GB `.fmp12` data file. I have been running it for over a couple of hours now (still running). Is there anyway to speed up the performance?

Thanks.
<img width="1109" alt="Screenshot 2022-12-12 at 7 38 30 PM" src="https://user-images.githubusercontent.com/133924/207198027-9de1a9a3-2738-40ba-a621-c4058a1e249b.png">

<img width="1423" alt="Screenshot 2022-12-12 at 7 38 56 PM" src="https://user-images.githubusercontent.com/133924/207198030-71d207d5-5f95-482b-b54f-4beb691585cd.png">

**Comment by evanmiller** [comment]
There's an option in libxlsxwriter to write directly to disk instead of holding the spreadsheet in memory. I'm guessing it will help here. The option is described in https://libxlsxwriter.github.io/working_with_memory.html

**Comment by evanmiller** [comment]
You also might try converting to a SQLite file to see if that's successful.

**Comment by ye** [comment]
Sounds good. I will report back when I give those two a try.

**Comment by evanmiller** [comment]
FYI I have made the `constant_memory` change to the master branch. Try pulling the latest code and see if it runs any better.

**Comment by evanmiller** [comment]
Please try the latest release and open a new issue if you continue to experience slowness.
